spring.application.name=sensores-vsc
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/vehiculos
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
server.port=8080

spring.datasource.password=${DB_PASSWORD:}